apiVersion: v1
kind: Service
metadata:
  name: notification-etcd
  namespace: notification-system
  labels:
    app: notification
    tier: etcd
    version: 0.1.0
spec:
  selector:
    app: notification
    tier: etcd
  ports:
  - name: tcp
    protocol: TCP
    port: 2379
    targetPort: 2379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-etcd-pvc
  namespace: notification-system
  labels:
    app: notification
    tier: etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: notification-etcd-deployment
  namespace: notification-system
  labels:
    app: notification
    tier: etcd
    version: 0.1.0
spec:
  selector:
    matchLabels:
      app: notification
      tier: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification
        tier: etcd
        version: 0.1.0
    spec:
      containers:
      - name: notification-etcd
        image: quay.io/coreos/etcd:v3.2.18
        imagePullPolicy: IfNotPresent
        command: ["etcd", "--data-dir=/data", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://notification-etcd.notification-system.svc:2379", "--max-snapshots=5", "--max-wals=5", "--auto-compaction-retention=168"]
        ports:
        - containerPort: 2379
          name: etcd
        volumeMounts:
        - name: etcd-persistent-storage
          mountPath: /data
      volumes:
      - name: etcd-persistent-storage
        persistentVolumeClaim:
          claimName: notification-etcd-pvc
