apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: kubesphere-alerting-system
  labels:
    app: notification
    component: notification
    version: v0.1.0
spec:
  selector:
    app: notification
    component: notification
  ports:
  - name:  notification
    protocol: TCP
    port: 9201
    targetPort: 9201
  - name:  swagger
    protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: notification-deployment
  namespace: kubesphere-alerting-system
  labels:
    app: notification
    component: notification
    version: v0.1.0
spec:
  selector:
    matchLabels:
      app: notification
      component: notification
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
        component: notification
        version: v0.1.0
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z notification-db.kubesphere-alerting-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z notification-etcd.kubesphere-alerting-system.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: notification
        image: openpitrix/notification:latest
        imagePullPolicy: Always
        command:
          - notification
        ports:
        - containerPort: 9201
          name: notification
        - containerPort: 9200
          name: swagger
        env:
        - name: NOTIFICATION_GRPC_SHOW_ERROR_CAUSE
          value: 'true'
        - name: NOTIFICATION_APP_HOST
          value: 'notification.kubesphere-alerting-system'
        - name: NOTIFICATION_APP_API_HOST
          value: 'notification.kubesphere-alerting-system'
        - name: NOTIFICATION_MYSQL_HOST
          value: 'openpitrix-db.openpitrix-system.svc'
        - name: NOTIFICATION_MYSQL_PORT
          value: '3306'
        - name: NOTIFICATION_ETCD_ENDPOINTS
          value: 'openpitrix-etcd.openpitrix-system.svc:2379'
        - name: NOTIFICATION_EMAIL_PROTOCOL
          value: 'SMTP'
        - name: NOTIFICATION_EMAIL_EMAIL_HOST
          value: 'mail.app-center.cn'
        - name: NOTIFICATION_EMAIL_PORT
          value: '25'
        - name: NOTIFICATION_EMAIL_DISPLAY_SENDER
          value: 'admin_openpitrix'
        - name: NOTIFICATION_EMAIL_EMAIL
          value: 'openpitrix@app-center.cn'
        - name: NOTIFICATION_EMAIL_PASSWORD
          value: 'openpitrix'
        - name: NOTIFICATION_EMAIL_SSL_ENABLE
          value: 'false'
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
