// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/nf.proto

// package nf;

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateNfWUserFilterRequest struct {
	NfPostType           *wrappers.StringValue `protobuf:"bytes,1,opt,name=nf_post_type,json=nfPostType,proto3" json:"nf_post_type,omitempty"`
	NotifyType           *wrappers.StringValue `protobuf:"bytes,2,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ShortContent         *wrappers.StringValue `protobuf:"bytes,5,opt,name=short_content,json=shortContent,proto3" json:"short_content,omitempty"`
	ExpiredDays          *wrappers.StringValue `protobuf:"bytes,6,opt,name=expired_days,json=expiredDays,proto3" json:"expired_days,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	UserFilterType       *wrappers.StringValue `protobuf:"bytes,8,opt,name=user_filter_type,json=userFilterType,proto3" json:"user_filter_type,omitempty"`
	UserFilterCondition  *wrappers.StringValue `protobuf:"bytes,9,opt,name=user_filter_condition,json=userFilterCondition,proto3" json:"user_filter_condition,omitempty"`
	UseridList           *wrappers.StringValue `protobuf:"bytes,10,opt,name=userid_list,json=useridList,proto3" json:"userid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateNfWUserFilterRequest) Reset()         { *m = CreateNfWUserFilterRequest{} }
func (m *CreateNfWUserFilterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNfWUserFilterRequest) ProtoMessage()    {}
func (*CreateNfWUserFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{2}
}

func (m *CreateNfWUserFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNfWUserFilterRequest.Unmarshal(m, b)
}
func (m *CreateNfWUserFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNfWUserFilterRequest.Marshal(b, m, deterministic)
}
func (m *CreateNfWUserFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNfWUserFilterRequest.Merge(m, src)
}
func (m *CreateNfWUserFilterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNfWUserFilterRequest.Size(m)
}
func (m *CreateNfWUserFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNfWUserFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNfWUserFilterRequest proto.InternalMessageInfo

func (m *CreateNfWUserFilterRequest) GetNfPostType() *wrappers.StringValue {
	if m != nil {
		return m.NfPostType
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetNotifyType() *wrappers.StringValue {
	if m != nil {
		return m.NotifyType
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetShortContent() *wrappers.StringValue {
	if m != nil {
		return m.ShortContent
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetExpiredDays() *wrappers.StringValue {
	if m != nil {
		return m.ExpiredDays
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetUserFilterType() *wrappers.StringValue {
	if m != nil {
		return m.UserFilterType
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetUserFilterCondition() *wrappers.StringValue {
	if m != nil {
		return m.UserFilterCondition
	}
	return nil
}

func (m *CreateNfWUserFilterRequest) GetUseridList() *wrappers.StringValue {
	if m != nil {
		return m.UseridList
	}
	return nil
}

type CreateNfResponse struct {
	// google.protobuf.StringValue nf_post_id = 1;
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNfResponse) Reset()         { *m = CreateNfResponse{} }
func (m *CreateNfResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNfResponse) ProtoMessage()    {}
func (*CreateNfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{3}
}

func (m *CreateNfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNfResponse.Unmarshal(m, b)
}
func (m *CreateNfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNfResponse.Marshal(b, m, deterministic)
}
func (m *CreateNfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNfResponse.Merge(m, src)
}
func (m *CreateNfResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNfResponse.Size(m)
}
func (m *CreateNfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNfResponse proto.InternalMessageInfo

func (m *CreateNfResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateNfWAppFilterRequest struct {
	NfPostType           *wrappers.StringValue `protobuf:"bytes,1,opt,name=nf_post_type,json=nfPostType,proto3" json:"nf_post_type,omitempty"`
	NotifyType           *wrappers.StringValue `protobuf:"bytes,2,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ShortContent         *wrappers.StringValue `protobuf:"bytes,5,opt,name=short_content,json=shortContent,proto3" json:"short_content,omitempty"`
	ExpiredDays          *wrappers.StringValue `protobuf:"bytes,6,opt,name=expired_days,json=expiredDays,proto3" json:"expired_days,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	AppId                *wrappers.StringValue `protobuf:"bytes,8,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppVersions          *wrappers.StringValue `protobuf:"bytes,9,opt,name=app_versions,json=appVersions,proto3" json:"app_versions,omitempty"`
	ClusterStatus        *wrappers.StringValue `protobuf:"bytes,10,opt,name=cluster_status,json=clusterStatus,proto3" json:"cluster_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateNfWAppFilterRequest) Reset()         { *m = CreateNfWAppFilterRequest{} }
func (m *CreateNfWAppFilterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNfWAppFilterRequest) ProtoMessage()    {}
func (*CreateNfWAppFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{4}
}

func (m *CreateNfWAppFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNfWAppFilterRequest.Unmarshal(m, b)
}
func (m *CreateNfWAppFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNfWAppFilterRequest.Marshal(b, m, deterministic)
}
func (m *CreateNfWAppFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNfWAppFilterRequest.Merge(m, src)
}
func (m *CreateNfWAppFilterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNfWAppFilterRequest.Size(m)
}
func (m *CreateNfWAppFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNfWAppFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNfWAppFilterRequest proto.InternalMessageInfo

func (m *CreateNfWAppFilterRequest) GetNfPostType() *wrappers.StringValue {
	if m != nil {
		return m.NfPostType
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetNotifyType() *wrappers.StringValue {
	if m != nil {
		return m.NotifyType
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetShortContent() *wrappers.StringValue {
	if m != nil {
		return m.ShortContent
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetExpiredDays() *wrappers.StringValue {
	if m != nil {
		return m.ExpiredDays
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetAppId() *wrappers.StringValue {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetAppVersions() *wrappers.StringValue {
	if m != nil {
		return m.AppVersions
	}
	return nil
}

func (m *CreateNfWAppFilterRequest) GetClusterStatus() *wrappers.StringValue {
	if m != nil {
		return m.ClusterStatus
	}
	return nil
}

type CreateNfWaddrsRequest struct {
	NfPostType           *wrappers.StringValue `protobuf:"bytes,1,opt,name=nf_post_type,json=nfPostType,proto3" json:"nf_post_type,omitempty"`
	NotifyType           *wrappers.StringValue `protobuf:"bytes,2,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ShortContent         *wrappers.StringValue `protobuf:"bytes,5,opt,name=short_content,json=shortContent,proto3" json:"short_content,omitempty"`
	ExpiredDays          *wrappers.StringValue `protobuf:"bytes,6,opt,name=expired_days,json=expiredDays,proto3" json:"expired_days,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	AddrsStr             *wrappers.StringValue `protobuf:"bytes,8,opt,name=addrs_str,json=addrsStr,proto3" json:"addrs_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateNfWaddrsRequest) Reset()         { *m = CreateNfWaddrsRequest{} }
func (m *CreateNfWaddrsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNfWaddrsRequest) ProtoMessage()    {}
func (*CreateNfWaddrsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{5}
}

func (m *CreateNfWaddrsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNfWaddrsRequest.Unmarshal(m, b)
}
func (m *CreateNfWaddrsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNfWaddrsRequest.Marshal(b, m, deterministic)
}
func (m *CreateNfWaddrsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNfWaddrsRequest.Merge(m, src)
}
func (m *CreateNfWaddrsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNfWaddrsRequest.Size(m)
}
func (m *CreateNfWaddrsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNfWaddrsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNfWaddrsRequest proto.InternalMessageInfo

func (m *CreateNfWaddrsRequest) GetNfPostType() *wrappers.StringValue {
	if m != nil {
		return m.NfPostType
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetNotifyType() *wrappers.StringValue {
	if m != nil {
		return m.NotifyType
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetShortContent() *wrappers.StringValue {
	if m != nil {
		return m.ShortContent
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetExpiredDays() *wrappers.StringValue {
	if m != nil {
		return m.ExpiredDays
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CreateNfWaddrsRequest) GetAddrsStr() *wrappers.StringValue {
	if m != nil {
		return m.AddrsStr
	}
	return nil
}

type DescribeNfsRequest struct {
	NfPostType           []string              `protobuf:"bytes,1,rep,name=nf_post_type,json=nfPostType,proto3" json:"nf_post_type,omitempty"`
	NotifyType           []string              `protobuf:"bytes,2,rep,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	UseridsStr           *wrappers.StringValue `protobuf:"bytes,6,opt,name=userids_str,json=useridsStr,proto3" json:"userids_str,omitempty"`
	Status               []string              `protobuf:"bytes,7,rep,name=status,proto3" json:"status,omitempty"`
	Limit                uint32                `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32                `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKey              *wrappers.StringValue `protobuf:"bytes,10,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DescribeNfsRequest) Reset()         { *m = DescribeNfsRequest{} }
func (m *DescribeNfsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeNfsRequest) ProtoMessage()    {}
func (*DescribeNfsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{6}
}

func (m *DescribeNfsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeNfsRequest.Unmarshal(m, b)
}
func (m *DescribeNfsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeNfsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeNfsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeNfsRequest.Merge(m, src)
}
func (m *DescribeNfsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeNfsRequest.Size(m)
}
func (m *DescribeNfsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeNfsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeNfsRequest proto.InternalMessageInfo

func (m *DescribeNfsRequest) GetNfPostType() []string {
	if m != nil {
		return m.NfPostType
	}
	return nil
}

func (m *DescribeNfsRequest) GetNotifyType() []string {
	if m != nil {
		return m.NotifyType
	}
	return nil
}

func (m *DescribeNfsRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *DescribeNfsRequest) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *DescribeNfsRequest) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *DescribeNfsRequest) GetUseridsStr() *wrappers.StringValue {
	if m != nil {
		return m.UseridsStr
	}
	return nil
}

func (m *DescribeNfsRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeNfsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeNfsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeNfsRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

type DescribeNfsResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeNfsResponse) Reset()         { *m = DescribeNfsResponse{} }
func (m *DescribeNfsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeNfsResponse) ProtoMessage()    {}
func (*DescribeNfsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{7}
}

func (m *DescribeNfsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeNfsResponse.Unmarshal(m, b)
}
func (m *DescribeNfsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeNfsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeNfsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeNfsResponse.Merge(m, src)
}
func (m *DescribeNfsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeNfsResponse.Size(m)
}
func (m *DescribeNfsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeNfsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeNfsResponse proto.InternalMessageInfo

func (m *DescribeNfsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Notification struct {
	NfPostId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=nf_post_id,json=nfPostId,proto3" json:"nf_post_id,omitempty"`
	NfPostType           *wrappers.StringValue `protobuf:"bytes,2,opt,name=nf_post_type,json=nfPostType,proto3" json:"nf_post_type,omitempty"`
	NotifyType           *wrappers.StringValue `protobuf:"bytes,3,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ShortContent         *wrappers.StringValue `protobuf:"bytes,6,opt,name=short_content,json=shortContent,proto3" json:"short_content,omitempty"`
	ExpiredDays          *wrappers.StringValue `protobuf:"bytes,7,opt,name=expired_days,json=expiredDays,proto3" json:"expired_days,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StatusTime           *timestamp.Timestamp  `protobuf:"bytes,10,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a52fecb8090647, []int{8}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNfPostId() *wrappers.StringValue {
	if m != nil {
		return m.NfPostId
	}
	return nil
}

func (m *Notification) GetNfPostType() *wrappers.StringValue {
	if m != nil {
		return m.NfPostType
	}
	return nil
}

func (m *Notification) GetNotifyType() *wrappers.StringValue {
	if m != nil {
		return m.NotifyType
	}
	return nil
}

func (m *Notification) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Notification) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Notification) GetShortContent() *wrappers.StringValue {
	if m != nil {
		return m.ShortContent
	}
	return nil
}

func (m *Notification) GetExpiredDays() *wrappers.StringValue {
	if m != nil {
		return m.ExpiredDays
	}
	return nil
}

func (m *Notification) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Notification) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Notification) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *Notification) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "pb.HelloReply")
	proto.RegisterType((*CreateNfWUserFilterRequest)(nil), "pb.CreateNfWUserFilterRequest")
	proto.RegisterType((*CreateNfResponse)(nil), "pb.CreateNfResponse")
	proto.RegisterType((*CreateNfWAppFilterRequest)(nil), "pb.CreateNfWAppFilterRequest")
	proto.RegisterType((*CreateNfWaddrsRequest)(nil), "pb.CreateNfWaddrsRequest")
	proto.RegisterType((*DescribeNfsRequest)(nil), "pb.DescribeNfsRequest")
	proto.RegisterType((*DescribeNfsResponse)(nil), "pb.DescribeNfsResponse")
	proto.RegisterType((*Notification)(nil), "pb.Notification")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreateNfWUserFilter(ctx context.Context, in *CreateNfWUserFilterRequest, opts ...grpc.CallOption) (*CreateNfResponse, error)
	CreateNfWAppFilter(ctx context.Context, in *CreateNfWAppFilterRequest, opts ...grpc.CallOption) (*CreateNfResponse, error)
	CreateNfWaddrs(ctx context.Context, in *CreateNfWaddrsRequest, opts ...grpc.CallOption) (*CreateNfResponse, error)
	DescribeNfs(ctx context.Context, in *DescribeNfsRequest, opts ...grpc.CallOption) (*DescribeNfsResponse, error)
	DescribeUserNfs(ctx context.Context, in *DescribeNfsRequest, opts ...grpc.CallOption) (*DescribeNfsResponse, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/pb.nf/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) CreateNfWUserFilter(ctx context.Context, in *CreateNfWUserFilterRequest, opts ...grpc.CallOption) (*CreateNfResponse, error) {
	out := new(CreateNfResponse)
	err := c.cc.Invoke(ctx, "/pb.nf/CreateNfWUserFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) CreateNfWAppFilter(ctx context.Context, in *CreateNfWAppFilterRequest, opts ...grpc.CallOption) (*CreateNfResponse, error) {
	out := new(CreateNfResponse)
	err := c.cc.Invoke(ctx, "/pb.nf/CreateNfWAppFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) CreateNfWaddrs(ctx context.Context, in *CreateNfWaddrsRequest, opts ...grpc.CallOption) (*CreateNfResponse, error) {
	out := new(CreateNfResponse)
	err := c.cc.Invoke(ctx, "/pb.nf/CreateNfWaddrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) DescribeNfs(ctx context.Context, in *DescribeNfsRequest, opts ...grpc.CallOption) (*DescribeNfsResponse, error) {
	out := new(DescribeNfsResponse)
	err := c.cc.Invoke(ctx, "/pb.nf/DescribeNfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) DescribeUserNfs(ctx context.Context, in *DescribeNfsRequest, opts ...grpc.CallOption) (*DescribeNfsResponse, error) {
	out := new(DescribeNfsResponse)
	err := c.cc.Invoke(ctx, "/pb.nf/DescribeUserNfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	CreateNfWUserFilter(context.Context, *CreateNfWUserFilterRequest) (*CreateNfResponse, error)
	CreateNfWAppFilter(context.Context, *CreateNfWAppFilterRequest) (*CreateNfResponse, error)
	CreateNfWaddrs(context.Context, *CreateNfWaddrsRequest) (*CreateNfResponse, error)
	DescribeNfs(context.Context, *DescribeNfsRequest) (*DescribeNfsResponse, error)
	DescribeUserNfs(context.Context, *DescribeNfsRequest) (*DescribeNfsResponse, error)
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_CreateNfWUserFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNfWUserFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateNfWUserFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/CreateNfWUserFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateNfWUserFilter(ctx, req.(*CreateNfWUserFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_CreateNfWAppFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNfWAppFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateNfWAppFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/CreateNfWAppFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateNfWAppFilter(ctx, req.(*CreateNfWAppFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_CreateNfWaddrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNfWaddrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateNfWaddrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/CreateNfWaddrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateNfWaddrs(ctx, req.(*CreateNfWaddrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_DescribeNfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeNfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).DescribeNfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/DescribeNfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).DescribeNfs(ctx, req.(*DescribeNfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_DescribeUserNfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeNfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).DescribeUserNfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.nf/DescribeUserNfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).DescribeUserNfs(ctx, req.(*DescribeNfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.nf",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Notification_SayHello_Handler,
		},
		{
			MethodName: "CreateNfWUserFilter",
			Handler:    _Notification_CreateNfWUserFilter_Handler,
		},
		{
			MethodName: "CreateNfWAppFilter",
			Handler:    _Notification_CreateNfWAppFilter_Handler,
		},
		{
			MethodName: "CreateNfWaddrs",
			Handler:    _Notification_CreateNfWaddrs_Handler,
		},
		{
			MethodName: "DescribeNfs",
			Handler:    _Notification_DescribeNfs_Handler,
		},
		{
			MethodName: "DescribeUserNfs",
			Handler:    _Notification_DescribeUserNfs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/nf.proto",
}

func init() { proto.RegisterFile("pb/nf.proto", fileDescriptor_88a52fecb8090647) }

var fileDescriptor_88a52fecb8090647 = []byte{
	// 1047 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0x26, 0xb1, 0x9d, 0x1c, 0x3b, 0x26, 0x4c, 0x7e, 0xea, 0x2c, 0x25, 0x31, 0x5b, 0x88,
	0x42, 0x95, 0xda, 0x6a, 0x8a, 0x40, 0x84, 0x3f, 0x39, 0xae, 0x2a, 0x2a, 0x22, 0x2b, 0x72, 0x4a,
	0xb9, 0x5c, 0xad, 0xbd, 0xb3, 0xce, 0x88, 0xf5, 0xce, 0xb0, 0x33, 0x6e, 0xba, 0xb7, 0xf0, 0x02,
	0xc8, 0x5c, 0x80, 0x84, 0xb8, 0xe1, 0x1d, 0x78, 0x07, 0xee, 0x79, 0x05, 0x5e, 0x81, 0x0b, 0xee,
	0xd0, 0xcc, 0xfe, 0x74, 0x6d, 0xc7, 0xed, 0x90, 0x5c, 0x54, 0x95, 0x7a, 0x65, 0xcf, 0xcc, 0xf9,
	0xce, 0x7e, 0x7b, 0xce, 0x77, 0xce, 0x9e, 0x81, 0x4d, 0xd6, 0x6b, 0x06, 0x54, 0x10, 0x8f, 0xf4,
	0x1d, 0x41, 0x68, 0xd0, 0x60, 0x21, 0x15, 0x14, 0x2d, 0xb0, 0x9e, 0x79, 0x73, 0x40, 0xe9, 0xc0,
	0xc7, 0x4d, 0x87, 0x91, 0xa6, 0x13, 0x04, 0x54, 0x28, 0x03, 0x1e, 0x5b, 0x98, 0x3b, 0xc9, 0xa9,
	0x5a, 0xf5, 0x46, 0x5e, 0xf3, 0x22, 0x74, 0x18, 0xc3, 0x61, 0x7a, 0x7e, 0xa0, 0x7e, 0xfa, 0x77,
	0x06, 0x38, 0xb8, 0xc3, 0x2f, 0x9c, 0xc1, 0x00, 0x87, 0x4d, 0xca, 0x94, 0x87, 0x4b, 0xbc, 0xed,
	0x4e, 0x7b, 0x13, 0x64, 0x88, 0xb9, 0x70, 0x86, 0x2c, 0x36, 0xb0, 0x2c, 0xa8, 0x7c, 0x89, 0x7d,
	0x9f, 0x76, 0xf1, 0x77, 0x23, 0xcc, 0x05, 0x42, 0xb0, 0x14, 0x38, 0x43, 0x5c, 0x33, 0xea, 0xc6,
	0xfe, 0x4a, 0x57, 0xfd, 0xb7, 0xf6, 0x00, 0x12, 0x1b, 0xe6, 0x47, 0xa8, 0x06, 0xa5, 0x21, 0xe6,
	0xdc, 0x19, 0xa4, 0x46, 0xe9, 0xd2, 0xfa, 0xa5, 0x00, 0x66, 0x3b, 0xc4, 0x8e, 0xc0, 0x1d, 0xef,
	0x9b, 0xaf, 0x39, 0x0e, 0x1f, 0x10, 0x5f, 0xe0, 0x30, 0x75, 0xfd, 0x39, 0x54, 0x02, 0xcf, 0x66,
	0x94, 0x0b, 0x5b, 0x44, 0x2c, 0x46, 0x97, 0x0f, 0x6f, 0x36, 0x62, 0x8a, 0x8d, 0x94, 0x62, 0xe3,
	0x4c, 0x84, 0x24, 0x18, 0x3c, 0x76, 0xfc, 0x11, 0xee, 0x42, 0xe0, 0x9d, 0x52, 0x2e, 0x1e, 0x45,
	0x0c, 0xa3, 0xcf, 0xa0, 0xac, 0x22, 0x1a, 0xc5, 0xf0, 0x05, 0x2d, 0xb8, 0x02, 0x28, 0xf8, 0x21,
	0x14, 0x04, 0x11, 0x3e, 0xae, 0x2d, 0x6a, 0x00, 0x63, 0x53, 0xf4, 0x21, 0x94, 0xfa, 0x34, 0x10,
	0x38, 0x10, 0xb5, 0x25, 0x0d, 0x54, 0x6a, 0x8c, 0x5a, 0xb0, 0xca, 0xcf, 0x69, 0x28, 0xec, 0x14,
	0x5d, 0xd0, 0x40, 0x57, 0x14, 0xa4, 0x9d, 0xb8, 0xf8, 0x02, 0x2a, 0xf8, 0x29, 0x23, 0x21, 0x76,
	0x6d, 0xd7, 0x89, 0x78, 0xad, 0xa8, 0xe1, 0xa1, 0x9c, 0x20, 0xee, 0x3b, 0x11, 0x97, 0xef, 0x4b,
	0x2f, 0x02, 0x1c, 0xd6, 0x4a, 0x3a, 0xef, 0xab, 0x4c, 0xd1, 0x03, 0x58, 0x1b, 0x71, 0x1c, 0xda,
	0x9e, 0x4a, 0x5c, 0x1c, 0xe7, 0x65, 0x0d, 0x78, 0x75, 0x94, 0x65, 0x5b, 0xc5, 0xfa, 0x14, 0x36,
	0xf3, 0x7e, 0xfa, 0x34, 0x70, 0x89, 0x94, 0x65, 0x6d, 0x45, 0xc3, 0xd9, 0xfa, 0x33, 0x67, 0xed,
	0x14, 0x28, 0x93, 0x2f, 0xb7, 0x89, 0x6b, 0xfb, 0x84, 0x8b, 0x1a, 0xe8, 0x24, 0x3f, 0x06, 0x9c,
	0x10, 0x2e, 0xac, 0x03, 0x58, 0x4b, 0x95, 0xd9, 0xc5, 0x9c, 0xd1, 0x80, 0xe3, 0xe7, 0x08, 0xf9,
	0xdf, 0x25, 0xd8, 0xce, 0x84, 0xdc, 0x62, 0xec, 0xb5, 0x8e, 0x5f, 0x31, 0x1d, 0xdf, 0x83, 0xa2,
	0xc3, 0x98, 0x4d, 0x5c, 0x2d, 0xf5, 0x16, 0x1c, 0xc6, 0x1e, 0xba, 0x92, 0xa9, 0x04, 0x3d, 0xc1,
	0x21, 0x97, 0x1d, 0x54, 0x4b, 0xab, 0x65, 0x87, 0xb1, 0xc7, 0x09, 0x00, 0xb5, 0xa1, 0xda, 0xf7,
	0x47, 0x5c, 0x2a, 0x9e, 0x0b, 0x47, 0x8c, 0xb8, 0x96, 0x4c, 0x57, 0x13, 0xcc, 0x99, 0x82, 0x58,
	0xff, 0x2c, 0xc2, 0x66, 0xa6, 0x3d, 0xc7, 0x75, 0x43, 0xfe, 0x5a, 0x77, 0xaf, 0x8c, 0xee, 0x3e,
	0x86, 0x15, 0x95, 0x32, 0x9b, 0x8b, 0x50, 0x4b, 0x7a, 0xcb, 0xca, 0xfc, 0x4c, 0x84, 0xd6, 0x1f,
	0x8b, 0x80, 0xee, 0x63, 0xde, 0x0f, 0x49, 0x0f, 0x77, 0xbc, 0x2c, 0xe9, 0xf5, 0x99, 0xa4, 0x2f,
	0xee, 0xaf, 0x4c, 0xa4, 0x75, 0x77, 0x3a, 0xad, 0xb1, 0xc1, 0xcb, 0x49, 0x5c, 0x16, 0xb4, 0x82,
	0x7e, 0xd0, 0xb2, 0xd6, 0x1e, 0x87, 0xad, 0xa8, 0xdf, 0xda, 0x65, 0xe0, 0xd0, 0x16, 0x14, 0x93,
	0x6a, 0x2b, 0xa9, 0x57, 0x4f, 0x56, 0x68, 0x03, 0x0a, 0x3e, 0x19, 0x12, 0xa1, 0xf2, 0xb0, 0xda,
	0x8d, 0x17, 0xd2, 0x9a, 0x7a, 0x1e, 0xc7, 0x42, 0x95, 0xf7, 0x6a, 0x37, 0x59, 0xa1, 0x8f, 0x60,
	0x99, 0x4b, 0xc1, 0x7d, 0x8b, 0x23, 0xad, 0xaa, 0x2d, 0x49, 0xeb, 0xaf, 0x70, 0x64, 0x35, 0x61,
	0x7d, 0x22, 0x6d, 0x2f, 0xfc, 0xb8, 0xfc, 0x56, 0x80, 0x4a, 0x27, 0x37, 0x19, 0xa2, 0x23, 0x80,
	0x34, 0xc5, 0xc4, 0xd5, 0xaa, 0xea, 0xe5, 0x38, 0xfd, 0x0f, 0xdd, 0x99, 0x9e, 0xb0, 0x70, 0xbd,
	0x9e, 0xb0, 0x78, 0xd5, 0x9e, 0xb0, 0x74, 0x25, 0x69, 0x15, 0xae, 0xd5, 0x13, 0x8a, 0xd7, 0xee,
	0x09, 0xa5, 0xff, 0xdb, 0x13, 0x3e, 0xc8, 0xb4, 0xa6, 0x53, 0xdc, 0xa9, 0x12, 0x3f, 0x81, 0x72,
	0x5f, 0x75, 0x74, 0x5b, 0x4e, 0xdf, 0xc9, 0x77, 0xc5, 0x9c, 0x81, 0x3e, 0x4a, 0x47, 0xf3, 0x2e,
	0xc4, 0xe6, 0x72, 0x43, 0x82, 0x63, 0x37, 0x31, 0x18, 0x5e, 0x0c, 0x8e, 0xcd, 0x15, 0x38, 0x2b,
	0xc7, 0xb2, 0x76, 0x39, 0x1e, 0xfe, 0x59, 0x84, 0x4a, 0xfe, 0xe6, 0x82, 0x8e, 0x61, 0xf9, 0xcc,
	0x89, 0xd4, 0x0d, 0x00, 0xad, 0x35, 0x58, 0xaf, 0x91, 0xbf, 0x30, 0x98, 0xd5, 0xdc, 0x0e, 0xf3,
	0x23, 0x6b, 0xe3, 0xfb, 0xbf, 0xfe, 0xfe, 0x69, 0xa1, 0x6a, 0xad, 0x34, 0x9f, 0xdc, 0x6d, 0x9e,
	0xcb, 0xfd, 0x23, 0xe3, 0x36, 0xfa, 0xd5, 0x80, 0xf5, 0x4b, 0xae, 0x06, 0x68, 0x47, 0xa2, 0xe7,
	0xdf, 0x19, 0xcc, 0x8d, 0xfc, 0x79, 0x5a, 0x5c, 0x56, 0x67, 0xdc, 0xda, 0x43, 0xef, 0xc6, 0x41,
	0xaa, 0xe7, 0xb9, 0xd6, 0x2f, 0x88, 0x38, 0xaf, 0x4b, 0x37, 0xf5, 0xd8, 0x8f, 0x22, 0xb3, 0x6b,
	0x99, 0x92, 0x4c, 0xe0, 0x35, 0x2f, 0x79, 0x92, 0x64, 0xf7, 0xb3, 0x01, 0x68, 0x76, 0xde, 0x43,
	0x6f, 0x4f, 0x90, 0x9b, 0x9e, 0x03, 0xe7, 0x70, 0x3b, 0x19, 0xb7, 0xde, 0x43, 0xb7, 0xe6, 0x72,
	0x6b, 0x31, 0x96, 0xa7, 0xb6, 0x63, 0x6d, 0x4f, 0x53, 0xcb, 0x9e, 0x23, 0x99, 0xfd, 0x6e, 0x40,
	0x75, 0x72, 0x1a, 0x40, 0xdb, 0x13, 0xac, 0xf2, 0x13, 0xc2, 0x1c, 0x46, 0xf6, 0xb8, 0xf5, 0x29,
	0x3a, 0x9a, 0xcb, 0x48, 0x79, 0xd8, 0xc7, 0x43, 0x87, 0xf8, 0xf1, 0xff, 0x83, 0x3a, 0x3b, 0xa7,
	0x01, 0xae, 0x07, 0xa3, 0x61, 0x0f, 0x87, 0xfc, 0x7d, 0x45, 0xd4, 0xb4, 0x36, 0xa7, 0x89, 0x2a,
	0x63, 0x49, 0xf2, 0x07, 0x03, 0xca, 0xb9, 0x1e, 0x88, 0xb6, 0x24, 0x8d, 0xd9, 0x6f, 0x99, 0x79,
	0x63, 0x66, 0x3f, 0x61, 0xd8, 0x1e, 0xb7, 0x6e, 0xa1, 0x77, 0xdc, 0xe4, 0xa4, 0xde, 0x99, 0xe1,
	0xe8, 0x3d, 0x8b, 0xd8, 0x0d, 0x0b, 0x25, 0x44, 0x72, 0x9e, 0x24, 0x8b, 0x1f, 0x0d, 0x78, 0x23,
	0xdd, 0x92, 0xe9, 0xbd, 0x12, 0x93, 0x93, 0x71, 0x6b, 0x1f, 0xed, 0x65, 0x4c, 0x94, 0x92, 0x9e,
	0x4b, 0xe7, 0x2d, 0x6b, 0x6b, 0x8a, 0x4e, 0xf2, 0xec, 0x23, 0xe3, 0xf6, 0xf1, 0x5d, 0x30, 0x09,
	0x6d, 0x50, 0x86, 0x03, 0x46, 0x44, 0x48, 0x9e, 0x36, 0xf2, 0xd1, 0x3f, 0x7e, 0x33, 0xbf, 0x3a,
	0x95, 0x15, 0x79, 0x6a, 0xf4, 0x8a, 0xaa, 0x34, 0xef, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9a,
	0x8e, 0x72, 0xec, 0x40, 0x10, 0x00, 0x00,
}
